services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=0.0.0.0 #optional
    volumes:
      - ${HOST_PATH}/installed/media_server/config:/config
      - mounts:/mnt
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    networks:
      messnet:
        ipv4_address: 172.14.0.11

networks:
  messnet:
    external: true

volumes:
  mounts:
    external:
      name: mounts