services:
  volume_initializer:
    image: alpine
    container_name: resourcemng
    privileged: true  # Ensures it can modify mount flags
    volumes:
      - mounts:/mnt
    restart: "no"
    entrypoint: >
      sh -c "mkdir -p /mnt/vods/Movie_VOD /mnt/vods/TV_VOD && chown -R ${PUID}:${PGID} /mnt && echo 'Directories initialized and ownership set to ${PUID}:${PGID}!'"

volumes:
  mounts:
    name: mounts