services:
  volume_initializer:
    image: alpine
    container_name: resourcemng
    volumes:
      - mounts:/mnt
    restart: "no"
    entrypoint: >
      sh -c "mkdir -p /mnt/jellyfin /mnt/jellyfin/movies /mnt/jellyfin/tv /mnt/remote && chown -R ${PUID}:${PGID} /mnt && echo 'Directories initialized and ownership set to ${PUID}:${PGID}!'"

volumes:
  mounts:
    name: mounts