version: '3.8'

services:
  mess:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mess
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - ./compose/:/app/compose/
      - ./media/:/app/media/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=production
      - MASTER_KEY=abcdefghijklmnopqrstuvwx
      - PUID=1000
      - PGID=1000
    restart: unless-stopped