version: '3.8'

services:
  mess:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mess
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./compose/:/app/compose/
    environment:
      - NODE_ENV=production
      - MASTER_KEY=abcdefghijklmnopqrstuvwx
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    networks:
      messnet:
        ipv4_address: 10.21.12.2

    privileged: true
    
networks:
  messnet:
    name: messnet
    ipam:
      driver: default
      config:
        - subnet: "10.21.12.0/26"