services:
  radarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=America/Los_Angeles
    volumes:
      - ${HOST_PATH}/installed/sonarr_app/config:/config
      - mounts:/mnt:rslave
    networks:
      messnet:
        ipv4_address: 10.21.12.12
    ports:
      - ${SONARR_PORT:-8989}:8989
    restart: unless-stopped
networks:
  messnet:
    external: true
    name: messnet

volumes:
  mounts:
    external: true
    name: mounts