services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_PATH}/dockge/data:/app/data
      - ${HOST_PATH}/installed:${HOST_PATH}/installed
    networks:
      messnet:
        ipv4_address: 10.21.12.8
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=${HOST_PATH}/installed

networks:
  messnet:
    external: true
    name: messnet